/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutenticadoDashboard: typeof import('./src/components/AutenticadoDashboard.vue')['default']
    DataTableArticulo: typeof import('./src/components/DataTableArticulo.vue')['default']
    DataTableCategoria: typeof import('./src/components/DataTableCategoria.vue')['default']
    DataTableUsuario: typeof import('./src/components/DataTableUsuario.vue')['default']
    HeaderNav: typeof import('./src/components/home/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecBanner: typeof import('./src/components/home/SecBanner.vue')['default']
    SecCasosExito: typeof import('./src/components/home/SecCasosExito.vue')['default']
    SecDescripcion: typeof import('./src/components/home/SecDescripcion.vue')['default']
    SecFooter: typeof import('./src/components/home/SecFooter.vue')['default']
    SecFormulario: typeof import('./src/components/home/SecFormulario.vue')['default']
    SecServicios: typeof import('./src/components/home/SecServicios.vue')['default']
    TheLogin: typeof import('./src/components/auth/TheLogin.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    ThePortafolio: typeof import('./src/components/ThePortafolio.vue')['default']
    TheRegistro: typeof import('./src/components/auth/TheRegistro.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VForm: typeof import('vuetify/lib')['VForm']
    VMain: typeof import('vuetify/lib')['VMain']
    VResponsive: typeof import('vuetify/lib')['VResponsive']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VTextField: typeof import('vuetify/lib')['VTextField']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
